volumes:
  pg_data_youtubeclone:

networks:
  amazon-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.190.5.0/26
    driver_opts:
      com.docker.network.bridge.name: br_amazon

services:
  amazon-backend:
    build: ./amazon-backend
    restart: always
    ports:
      - "8966:8966"
    volumes:
      - ./amazon-backend:/hdd/Dev/Amazon-Clone/amazon-backend
      - ./amazon-backend/node_modules:/hdd/Dev/Amazon-Clone/amazon-backend/node_modules
    env_file: 
      - ./amazon-backend/.env
    networks:
      - amazon-network
    # environment:
    #   DEBUG: 'true'
  amazon-frontend:
    build: ./amazon-frontend
    restart: always
    ports:
      - "8965:8965"
    volumes:
      - ./amazon-frontend:/hdd/Dev/Amazon-Clone/amazon-frontend
      - ./amazon-frontend/node_modules:/hdd/Dev/Amazon-Clone/amazon-frontend/node_modules
    env_file: 
      - ./amazon-frontend/.env
    networks:
      - amazon-network
    # environment:
    #   DEBUG: 'true'
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "9086:80"
    networks:
      - amazon-network
    volumes:
      - ./public:/hdd/Dev/Amazon-Clone/amazon-backend/public